default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 12345
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: brandsapp_development

test:
  <<: *default
  database: brandsapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

